### ISSUE TITLE
Investigate Github pages for making nicer visuals

### ISSUE THREAD

**Issue by bobek** [mayadata-io/culture#119]
Leverage [Github Pages](https://pages.github.com/) to generate a nicer rendering of the content, so people can browse and search etc.

**Comment by arne-rusek** [comment]
The [workflow](https://github.com/mayadata-io/culture/blob/master/.github/workflows/markdown.yaml) I've recently created uses `remark` which can render into HTML out of the box. Moreover I was looking into `toc` plugin which I wanted to use, but that actually works only for rendering to HTML. So displaying this rendered html should be relatively easy. Not sure about search.

**Comment by bobek** [comment]
I actually have a prototype based on `mdbook` basically done, I just got snowed under other stuff. You can check the output at 

https://bobek.github.io/culture/

**Comment by bobek** [comment]
Changes to the repository settings looks like this ![image](https://user-images.githubusercontent.com/26891/100926003-0b7e9e00-34e3-11eb-9173-b2119897ee23.png).
